version: '3.8'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./tmp/data/db:/data/db
  backend:
    build: backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/test
  front:
    build: frontend
    ports:
      - "3000:3000"